 The program operates a metronome using timers, and accepts pulses to pause the metronome for a number of seconds. 
 To avoid noisy chaos in the lab, we’ll use visual output for the “click” of the metronome.
 The program operates a metronome using timers, and accepts pulses to pause the metronome for a number of seconds. 
 To avoid noisy chaos in the lab, we’ll use visual output for the “click” of the metronome.
